version: '3.9'

services:
  rustapp:
    container_name: rustapp
    image: Slogulai/rustapp:1.0.0
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      DATABASE_URL: mysql://user:password123@db:3306/rust_axum_sqlx
    ports:
      - '3000:3000'
    depends_on: 
      - db
  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass 
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: rust_axum_sqlx
    ports:
      - '3306:3306'
    volumes: 
      - mysqldata:/var/lib/mysql

volumes: 
  mysqldata: {}
